export const titles = {
    'camovo-drvo': 'Čamovo drvo',
    'drvo-aluminijum': 'Drvo aluminijum',
    'drveni-kapak': 'Drveni kapak',
    'ulazna-vrata-puno-drvo': 'Ulazna vrata od punog drveta',
    'medijapan-folija': 'Medijapan folija',
    'medijapan-farbani': 'Medijapan farbani',
    'medijapan-furnirani': 'Medijapan furnirani',
    'unutrasnja-vrata-puno-drvo': 'Unutrašnja vrata od punog drveta',
    'velux-ovlasceni-prodavac': 'Velux',
    'velux-standard-drvo': 'Velux standard drvo',
    'velux-standard-beli': 'Velux standard beli',
    'velux-standard-plus-drvo': 'Velux standard plus drvo',
    'velux-standard-plus-beli': 'Velux standard plus beli',
    'velux-zastita-svetlost': 'Velux zaštita od svetlosti',
    'velux-zastita-toplota': 'Velux zaštita od toplote',
};
